WebApp/WebApp/Controllers/MakeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.AppDbContext;
using WebApp.Models;

namespace WebApp.Controllers
{
    [Authorize(Roles ="Admin")]
    public class MakeController : Controller
    {
        private readonly VroomDbContext _db;

        public MakeController(VroomDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.Makes.ToList());
        }

        //Http GET Method
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Make make)
        {
            if(ModelState.IsValid)
            {
                _db.Makes.Add(make);
                _db.SaveChanges();
                TempData["save"] = "Make  have been saved";
                return RedirectToAction(nameof(Index));
            }
            return View(make);
        }


        [HttpPost]
        public IActionResult Delete(int id)
        {
            var make = _db.Makes.Find(id);
            if(make == null)
            {
                return NotFound();
            }
            _db.Makes.Remove(make);
            _db.SaveChanges();
            TempData["delet"] = "Make have been deleted";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var make = _db.Makes.Find(id);
            if (make == null)
            {
                return NotFound();
            }
            return View(make);
        }

        [HttpPost]
        public IActionResult Edit(Make make)
        {
            if (ModelState.IsValid)
            {
                _db.Update(make);
                _db.SaveChanges();
                TempData["update"] = "Make  have been update";
                return RedirectToAction(nameof(Index));
            }
            return View(make);
        }
    }
}

WebApp/WebApp/Controllers/TechController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.AppDbContext;
using WebApp.Models;
using WebApp.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using cloudscribe.Pagination.Models;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TechController : Controller
    {
        private readonly VroomDbContext _db;
        private readonly IHostingEnvironment _ihostingEnvironment;

        [BindProperty]
        public TechViewModel TechVM { get; set; }

        public TechController(VroomDbContext db, IHostingEnvironment ihostingEnvironment)
        {
            _db = db;
            _ihostingEnvironment = ihostingEnvironment; 
            TechVM = new TechViewModel()
            {
                Makes = _db.Makes.ToList(),
                Models = _db.Models.ToList(),
                Tech = new Models.Tech()
            };
        }

        [AllowAnonymous]
        public IActionResult Index(string searchString, string sortOrder, int pageNumber=1, int pageSize=2)
        {
            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            ViewBag.PriceSortParam = String.IsNullOrEmpty(sortOrder) ? "price_desc" : "";
            int ExcludeRecord = (pageSize * pageNumber) - pageSize;

            var Techs = from b in _db.Teches.Include(m => m.Make).Include(m => m.Model)
                        select b;

            var TechCount = Techs.Count();

            if (!String.IsNullOrEmpty(searchString))
            {
                Techs = Techs.Where(b => b.Make.Name.Contains(searchString));
                TechCount = Techs.Count();
            }

            //Sorting Logic
            switch(sortOrder)
            {
                case "price_desc":
                    Techs = Techs.OrderByDescending(b => b.Price);
                    break;
                default:
                    Techs = Techs.OrderBy(b => b.Price);
                    break;
            }


            Techs = Techs
                .Skip(ExcludeRecord)
                .Take(pageSize);

            var result = new PagedResult<Tech>
            {
                Data = Techs.AsNoTracking().ToList(),
                TotalItems = TechCount,
                PageNumber = pageNumber,
                PageSize = pageSize,
            };
            return View(result);
        }

        //GET MEthod
        public IActionResult Create()
        {
            return View(TechVM);
        }

        //Post
        [HttpPost, ActionName("Create")]
        //[ValidateAntiForgeryToken]
        public IActionResult CreatePost()
        {
            if (!ModelState.IsValid)
            {
                TechVM.Makes = _db.Makes.ToList();
                TechVM.Models = _db.Models.ToList();
                return View(TechVM);
            }
            _db.Teches.Add(TechVM.Tech);
            _db.SaveChanges();
            UploadImageIfAvailable();
            TempData["save"] = "Tech type have been saved";
            return RedirectToAction(nameof(Index));
        }

        private void UploadImageIfAvailable()
        {

            //Get Tech id we have in database
            var TechID = TechVM.Tech.Id;

            //Get root path to save the file on the server 
            string wwrootPath = _ihostingEnvironment.WebRootPath;

            //Get the uploaded files
            var files = HttpContext.Request.Form.Files;

            //Get the references of DBSet in database
            var SaveTech = _db.Teches.Find(TechID);

            //Upload the files on server and save the path image
            if (files.Count != 0)
            {
                var ImgPath = @"images\tech";
                var Extension = Path.GetExtension(files[0].FileName);
                var RelativeImgPath = ImgPath + TechID + Extension;
                var AbsImgPath = Path.Combine(wwrootPath, RelativeImgPath);

                //Upload the file on the server
                using (var fileStream = new FileStream(AbsImgPath, FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                //set the path on database
                SaveTech.ImagePath = RelativeImgPath; _db.SaveChanges();
            }
        }

        
        public IActionResult Edit(int id)
        {
            TechVM.Tech = _db.Teches.Include(m => m.Make).SingleOrDefault(m => m.Id == id);

            //Filter the models 
            TechVM.Models = _db.Models.Where(m => m.MakeFK == TechVM.Tech.ModelFK);

            if (TechVM.Tech == null)
            {
                return NotFound();
            }
            return View(TechVM);
        }   

        [HttpPost, ActionName("Edit")]
        public IActionResult EditPost()
        {
            if (!ModelState.IsValid)
            {
                TechVM.Makes = _db.Makes.ToList();
                TechVM.Models = _db.Models.ToList();
                return View(TechVM);
            }
            _db.Teches.Update(TechVM.Tech);
            UploadImageIfAvailable();
            _db.SaveChanges();
            TempData["update"] = "Product type have been update";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            Tech tech = _db.Teches.Find(id);
            if (tech == null)
            {
                return NotFound();
            }
            _db.Teches.Remove(tech);
            _db.SaveChanges();
            TempData["delet"] = "Product type have been deleted";
            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        public IActionResult View(int id)
        {
            TechVM.Tech = _db.Teches.Include(m => m.Make).SingleOrDefault(m => m.Id == id);

            if (TechVM.Tech == null)
            {
                return NotFound();
            }
            return View(TechVM);
        }
    }
}

WebApp/WebApp/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="btn-group" rold="group">
    <form method="get" action="Edit">
        <button type="submit" class="btn btn-primary" asp-action="Edit" asp-route-id="@Model"><i class="fas fa-edit"></i></button>
    </form>
    <form method="post" action="Delete">
        <button onclick="if (!confirm('Are you sure you want to delete this Make?')) { return false }" type="submit" class="btn btn-danger rounded-0" asp-action="Delete" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></button>
    </form>
</div>

WebApp/WebApp/Views/Shared/_Layout.cshtml
@using WebApp.Helpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body style="background-color:darkgray">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" asp-controller="Tech" asp-action="Index">Vroom</a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Tech" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    @if (User.IsInRole(Roles.Admin)|| User.IsInRole(Roles.Executive))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Masters
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Make" asp-action="Index">Makes</a>
                                <a class="dropdown-item" asp-controller="ModelController1" asp-action="Index">Models</a>
                                <a class="dropdown-item" asp-controller="Tech" asp-action="Index">Technological Parts</a>
                                @if (User.IsInRole(Roles.Admin))
                                {
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Add User</a>
                                }
                            </div>
                        </li>
                        }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/WebApp/Views/Shared/_MakeButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="btn-group" rold="group">
    <form method="get" action="Edit">
        <button type="submit" class="btn btn-primary" asp-action="Edit" asp-route-id="@Model"><i class="fas fa-edit"></i></button>
    </form>
    <form method="post" action="Delete">
        <button onclick="if (!confirm('Are you sure you want to delete this Make?')) { return false }" type="submit" class="btn btn-danger rounded-0" asp-action="Delete" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></button>
    </form>
</div>

WebApp/WebApp/Views/Shared/_PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber=(int)Model.PageNumber
          cs-paging-totalitems=(int)Model.TotalItems
          cs-paging-pagesize=Model.PageSize
          cs-pagenumber-param="pagenumber"
          asp-route-searchString="@ViewBag.CurrentFilter"
          asp-route-sortOrder="@ViewBag.CurrentSortOrder"
          asp-controller=@ViewData["Controller"]
          asp-action=@ViewData["Action"]
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link">

</cs-pager>